version: "3"

services:
  app:
    build: .
    restart: always
    ports:
      - 4000:4000
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongodb:27017/knowledge-boost-api
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
